### PR TITLE
show container status of each node in docker info

### LINKED ISSUE #2141: docker info: display number of running containers per node
When running `docker info`:

```
# docker info
docker info
Containers: 124
 Running: 124
 Paused: 0
 Stopped: 0
Images: 248
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 node-122: 1.2.3.4:2376
  └ Status: Healthy
  └ Containers: 58
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.053 GiB
  └ Labels: app=1, executiondriver=native-0.2, kernelversion=4.2.0-30-generic, operatingsystem=Ubuntu 15.10, provider=generic, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-19T10:17:35Z
[...]
```

... the output contains the count of all containers, including i.e. exited ones. I'd propose to add the number of runnings containers also, like

```
  └ Containers: 58 (40 running)
```

Related: https://github.com/docker/swarm/issues/2096

### PR DESCRIPTION
**Pull request by allencloud**
1.Show container status of each node in `docker info`
2. add integration test cases in info.bats

Details:
If engine's status is not healthy, skip it.
```
...
Nodes: 1
 ubuntu: 10.1.0.108:2376
  └ Status: Healthy
  └ Containers: 1 (1 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-25T06:58:36Z
  └ ServerVersion: 1.11.0
...
```
Fixed #2141

Signed-off-by: Sun Hongliang <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by nishanttotla** [comment]
This looks fine, but I'm concerned that this increases the size of the output making it harder to read. Perhaps indicating running containers in a bracket like suggested in the issue?

Ping @vieux @dongluochen WDYT?

**Comment by allencloud** [comment]
@nishanttotla 
Yes， Increase the `docker info` output size a lot. And now I am on the side that adding a bracket like suggested.

**Comment by allencloud** [comment]
WDYT? @vieux @dongluochen @nishanttotla 
Any update?

File: cluster/swarm/cluster.go [hunk 1]
```diff
@@ -865,7 +865,23 @@ func (c *Cluster) Info() [][2]string {
 		info = append(info, [2]string{" " + engineName, engine.Addr})
 		info = append(info, [2]string{"  └ ID", engine.ID})
 		info = append(info, [2]string{"  └ Status", engine.Status()})
-		info = append(info, [2]string{"  └ Containers", fmt.Sprintf("%d", len(engine.Containers()))})
+		// if engine's status is healthy, show container details of the node
+		if engine.Status() == "Healthy" {
```
Comment (dongluochen) [inline cluster/swarm/cluster.go]: => 
`if engine.IsHealthy() {`

Comment (allencloud) [inline cluster/swarm/cluster.go]: Thanks @dongluochen 
Reasonable, updated that.

**Comment by dongluochen** [comment]
LGTM.

**Comment by allencloud** [comment]
PTAL @nishanttotla @vieux @abronan @jimmyxian

**Comment by allencloud** [comment]
ping @nishanttotla @vieux @abronan @jimmyxian  
WDYT?

**Comment by yank1** [comment]
LGTM

**Comment by jjyr** [comment]
We are looking forward this feature!! 👍

**Comment by jimmyxian** [comment]
LGTM
