### PR TITLE
Ignore 404 error from old engine versions

### LINKED ISSUE #1727: docker info with engine 1.6.2
I was testing 1.6.2 compat, seems ok beside one small thing:

```
./docker-1.6.2 info
Containers: 2
Images: 1
Storage Driver:
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 dev: :4242
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 4.053 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: 404 page not found

  └ UpdatedAt: 2016-01-29T14:16:02Z
Execution Driver:
Kernel Version: 3.19.0-25-generic
Operating System: linux
CPUs: 4
Total Memory: 4.053 GiB
```

The Error is

``` 
404 page not found

```

(with a \n)

I think it could lead us to problems.

@dongluochen can you take a look ?

### PR DESCRIPTION
**Pull request by dongluochen**
Ignore 404 error. Also remove trailing white spaces from error, including new lines.

Fix #1727. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

File: cluster/engine.go [hunk 1]
```diff
@@ -342,6 +342,13 @@ func (e *Engine) CheckConnectionErr(err error) {
 		return
 	}
 
+	// Docker engine may return 404 when it doesn't recognize a command.
+	// It's not an error from the engine itself. Version validation should be done separately.
+	// This error message is not recorded here to avoid user confusion.
+	if strings.HasPrefix(err.Error(), "404 ") {
```
Comment (nishanttotla) [inline cluster/engine.go]: Why are we testing for a prefix at all, instead of the exact error message?

Comment (dongluochen) [inline cluster/engine.go]: Thanks @nishanttotla for the comment. Actually I want to change it to record only selected few errors, and ignore others because the error itself is not self-contained, i.e., they are not clear without request info. For example, vm7 runs docker engine 1.6.2 and returns error `500 Internal Server Error: image ID '' is invalid` from `docker run hello-world`. It falls in the same category as #1727.  
```
 vm7: xxx.xxx.xxx.xxx:4444
  └ Status: Healthy
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.053 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: 500 Internal Server Error: image ID '' is invalid
  └ UpdatedAt: 2016-02-02T04:43:19Z
```

**Comment by vieux** [comment]
LGTM

**Comment by dongluochen** [comment]
Error message from node info is for CLI user. Most error messages are not self-contained, i.e., they are not clear without request info. #1724 error `404 page not found` is actually for some specific commands like `docker network ls` as Engine 1.6.2 doesn't support it. Another example, vm7 runs docker engine 1.6.2 and returns error `500 Internal Server Error: image ID '' is invalid` from `docker run hello-world`. Without the context (version, command) the error message would confuse user. I think it better to record only selected errors, and ignore others. 
```
 vm7: xxx.xxx.xxx.xxx:4444
  └ Status: Healthy
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.053 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: 500 Internal Server Error: image ID '' is invalid
  └ UpdatedAt: 2016-02-02T04:43:19Z
```

**Comment by nishanttotla** [comment]
LGTM.

@dongluochen can you explain what you mean by #1724 error?

Also, in general, I'm concerned that we don't handle API versions very well in Swarm, and they have little to do with API updates in Engine. We should fix that in general, which might help with further issues like this.

**Comment by dongluochen** [comment]
@nishanttotla It was my typo in previous message. I meant errors similar to #1727.

**Comment by abronan** [comment]
LGTM
