### PR TITLE
Swarm manager should retry EventMonitoring on failure

### LINKED ISSUE #1976: Swarm does not retry on event monitoring failure
Swarm manager may lose events from some nodes. The issue is swarm manager doesn't retry the connection, or fail the node. 
```
time="2016-03-15T21:07:56Z" level=error msg="Error monitoring events: Get https://10.0.0.120:12376/v1.15/events: dial tcp 10.0.0.120:12376: getsockopt: connection refused" id="xxxx" name=node-1
```

### PR DESCRIPTION
**Pull request by dongluochen**
Fix #1976.

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

File: cluster/engine.go [hunk 1]
```diff
@@ -183,10 +183,13 @@ func (e *Engine) StartMonitorEvents() {
...
-			log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Errorf("Error monitoring events: %s", err)
-		} else if err != nil {
-			log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Debug("EOF monitoring events, restarting")
+		if err := <-ec; err != nil {
+			log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Errorf("Error monitoring events: %s.", err)
+			if !strings.Contains(err.Error(), "EOF") {
+				// failing node reconnect should use back-off strategy
+				<-e.refreshDelayer.Wait(e.failureCount)
+			}
+			log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Errorf("Restart event mornitoring.")
```
Comment (nishanttotla) [inline cluster/engine.go]: Typo: `mornitoring` -> `monitoring`

**Comment by nishanttotla** [comment]
LGTM
