### PR TITLE
do not generate JSON by hand

### LINKED ISSUE #1110: Better message when Hub throws an error - in this case Hub was rate limiting requests
# Problem
If I do a pull from a single host when Hub is rate limited you get the following message

```
docker pull alvinr/interlock-haproxy
Error response from daemon: Get https://registry-1.docker.io/v2/alvinr/interlock-haproxy/manifests/latest: token auth attempt for registry: https://auth.docker.io/token?account=alvinr&scope=repository%3Aalvinr%2Finterlock-haproxy%3Apush%2Cpull&service=registry.docker.io request failed with status: 429 Too Many Requests
```

However, if you are pointing at a swarm cluster you get the following
```
vero:prod$ docker pull alvinr/interlock-haproxy
Using default tag: latest
swarm-0: Pulling alvinr/interlock-haproxy:latest... 
swarm-2: Pulling alvinr/interlock-haproxy:latest... 
swarm-3: Pulling alvinr/interlock-haproxy:latest... 
swarm-4: Pulling alvinr/interlock-haproxy:latest... 
invalid character '\n' in string literal
```

# Solution
Ensure that the error gets propagated back to the user

# Environment

```
uname -a
Linux swarm-0 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

```
docker-version
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2c16229
 Built:        Tue Jul 28 21:35:33 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2c16229
 Built:        Tue Jul 28 21:35:33 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

```
docker info
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2c16229
 Built:        Tue Jul 28 21:35:33 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2c16229
 Built:        Tue Jul 28 21:35:33 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
vero:prod$ docker-machine ssh swarm-0 "docker info"
Containers: 2
Images: 8
Storage Driver: aufs
 Root Dir: /mnt/data/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Docker version 1.7.1, build 786b29d
CPUs: 1
Total Memory: 1000 MiB
Name: swarm-0
ID: GOSW:5ULW:AFYE:YQ4X:RX4S:54R2:ZYIK:G6C5:U6W3:FJ6J:A6PD:ETCP
Labels:
 provider=vmwarefusion
Experimental: true
```

### PR DESCRIPTION
**Pull request by vieux**
fix #1110

### CODE REVIEW

**Comment by vieux** [comment]
@jimmyxian can you please check the load ? I removed some "\n" that I think were incorrect.
Also the callback is only called in case of an error, is this expected ? It means you have no output in case of succes.

File: api/utils.go [hunk 1]
```diff
@@ -20,6 +21,19 @@ func httpError(w http.ResponseWriter, err string, status int) {
 	http.Error(w, err, status)
 }
 
+func sendJSONMessage(w io.Writer, id, status string) {
+	message := struct {
```
Comment (vieux) [inline api/utils.go]: I decided to NOT import `docker/docker/pkg/jsonmessage` because it would required vendoring 3 pkgs (including term) it seemed overkill

**Comment by jimmyxian** [comment]
@vieux 
Aha, you can see this https://github.com/docker/swarm/pull/609#issuecomment-92579366
In order to keep output same as docker, I removed the output in case of success. :)
But I think we should add some successfull message when load in docker and swarm, any thoughts?

**Comment by vieux** [comment]
@jimmyxian it seems fine to me if it's like docker, but in the callback there is a `if status == ""` we could remove it as the status is never "", always an error)

**Comment by jimmyxian** [comment]
:+1: Yeah....My bad...should be removed

File: api/handlers.go [hunk 2]
```diff
@@ -410,9 +410,9 @@ func postImagesLoad(c *context, w http.ResponseWriter, r *http.Request) {
 	wf := NewWriteFlusher(w)
 	callback := func(what, status string) {
 		if status == "" {
```
Comment (jimmyxian) [inline api/handlers.go]: Here we have to use string(Not a json):
fmt.Fprintf(wf, "%s:Loading Image... %s", what, status)

**Comment by jimmyxian** [comment]
@vieux I have test `pull` and `import`, but the output seems not ok:
```
[root@host82 home]# docker -H  127.0.0.1:2222 pull test
Host82: Pulling test:latest... : Error: image library/test:latest not found 
Host80: Pulling test:latest... : Error: image library/test:latest not found 
[root@host82 home]# :latest... 


[root@host82 home]# docker -H  127.0.0.1:2222 pull busybox
Host80: Pulling busybox:latest... : downloaded 
Host82: Pulling busybox:latest... : downloaded 
[root@host82 home]# box:latest...


[root@host82 home]# docker -H  127.0.0.1:2222 import - < busybox_ex.tar

Host80: Import success 
[root@host82 home]# ss
```
I don't know  whether it related to my environment or other problem. Can you try on your environment ?

**Comment by vieux** [comment]
I tested and it's ok for me. @aluzzardi @abronan can you test ?

File: api/handlers.go (hunk 2 above)
Comment (vieux) [inline api/handlers.go]: can you open a PR after we merge this one ? Thanks

Comment (jimmyxian) [inline api/handlers.go]: OK

**Comment by vieux** [comment]
ping @abronan

**Comment by abronan** [comment]
@vieux will do

**Comment by abronan** [comment]
@vieux I confirm that this works for me too.

**Comment by vieux** [comment]
ping @aluzzardi
