### PR TITLE
change the way of producing engine label

### LINKED ISSUE #2201: With `docker info`, Swarm shows empty label of `executiondriver`
HI, All

When I execute `docker info` against docker 1.11.0 in Swarm 1.2.1, **empty** label of `executiondriver` shows up like below:
```
root@ubuntu:/home/daocloud# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 47
Server Version: swarm/1.2.1
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 ubuntu: 10.1.0.108:2376
  └ ID: RDEJ:ZCV6:CJH5:UCNB:P5RR:66LB:JZSO:YACX:TBL3:PYMV:2F77:KBUA
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 1 / 1
  └ Reserved Memory: 8 GiB / 2.052 GiB
  └ Labels: executiondriver=, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-03T10:11:53Z
  └ ServerVersion: 1.11.0
Plugins:
 Volume:
 Network:
Kernel Version: 3.19.0-25-generic
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 2.052 GiB
Name: ubuntu
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```

`docker info` against docker 1.11.0:
```
root@ubuntu:/home/daocloud# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 62
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 414
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: RDEJ:ZCV6:CJH5:UCNB:P5RR:66LB:JZSO:YACX:TBL3:PYMV:2F77:KBUA
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by allencloud**
Swarm has its way to construct engine labels. However docker daemon changes a little in its api.
For instance:
docker 1.10.3 has a field `ExecutionDriver` in `info` api:
https://github.com/docker/docker/blob/v1.10.3/daemon/info.go#L88
while, docker 1.11.0 has no field `ExecutionDriver` in `info` api:
https://github.com/docker/docker/blob/v1.11.0/daemon/info.go#L70-L107
As a result, swarm should change a little in that case.

And this PR did:
1. validate label if it is empty;
2. fix a typo when judging whether it is a label with key `node`
3. when user-provided engine labels have overlap with swarm specific labels, send a warn log and override the latter ones 
4. fix a typo in engine_test.go
5. add several unit tests in engine_test.go

This pr will make the `continuous-integration/travis-ci/pr` show a lot of Warning logs. 
Maybe need optimized?

Fixed #2201 

Signed-off-by: Sun Hongliang <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by allencloud** [comment]
unit test file ./replication.bats, line 187
Usually ran into error, seems something wrong it it. 
Maybe some improvement is needed in that.

**Comment by allencloud** [comment]
any update? @vieux @dongluochen @nishanttotla 
Any design review or more ?

File: cluster/engine.go [hunk 1]
```diff
@@ -513,9 +521,13 @@ func (e *Engine) updateSpecs() error {
 		// since "node" in constraint will match node.Name instead of label.
 		// Log warn message in this case.
 		if kv[0] == "node" {
-			log.Warnf("Engine (ID: %s, Addr: %s) containers a label (%s) with key of \"node\" which cannot be used in Swarm.", e.ID, e.Addr, label)
+			log.Warnf("Engine (ID: %s, Addr: %s) contains a label (%s) with key of \"node\" which cannot be used in Swarm.", e.ID, e.Addr, label)
+			continue
 		}
 
+		if value, exist := e.Labels[kv[0]]; exist {
+			log.Warnf("Engine (ID: %s, Addr: %s) already contains a label (%s) with key (%s), and Swarm will override it with docker engine label (%s)", e.ID, e.Addr, value, kv[0], kv[1])
```
Comment (dongluochen) [inline cluster/engine.go]: I think it better reject such labels. It's very likely a user mistake, e.g., user shouldn't set 'opertingsystem'.

Comment (allencloud) [inline cluster/engine.go]: Thanks @dongluochen 
Then how to deal missing executiondriver in docker 1.11.0 or higher?

Comment (dongluochen) [inline cluster/engine.go]: User can add executiondriver as label because the Engine doesn't have it from 1.11.0. But _changing_ Engine settings might be an error.

**Comment by allencloud** [comment]
Updated the code.
And forbid docker engine's label to override labels reserved for swarm node.
@dongluochen

**Comment by yank1** [comment]
LGTM

**Comment by allencloud** [comment]
Any update? ping @dongluochen @nishanttotla @jimmyxian @abronan

**Comment by abronan** [comment]
LGTM

ping @nishanttotla @dongluochen

File: cluster/engine_test.go [hunk 2]
```diff
@@ -222,14 +222,21 @@ func TestEngineSpecs(t *testing.T) {
...
-	assert.Equal(t, engine.Labels["kernelversion"], mockInfo.KernelVersion)
-	assert.Equal(t, engine.Labels["operatingsystem"], mockInfo.OperatingSystem)
+	mockInfo2 := mockInfo
+	mockInfo2.Labels = []string{"foo=bar", "executiondriver=newdriver", "node=node1"}
+
+	assert.Equal(t, engine.Cpus, int64(mockInfo2.NCPU))
+	assert.Equal(t, engine.Memory, mockInfo2.MemTotal)
+	assert.Equal(t, engine.Labels["storagedriver"], mockInfo2.Driver)
+
+	assert.Equal(t, engine.Labels["executiondriver"], "execution-driver-test")
```
Comment (nishanttotla) [inline cluster/engine_test.go]: @allencloud shouldn't this be `mockInfo2.ExecutionDriver`, to make sure it's future proof?

**Comment by dongluochen** [comment]
LGTM after fixing test constant mentioned by @nishanttotla .

**Comment by allencloud** [comment]
Updated. PTAL @dongluochen @nishanttotla @abronan, thanks.

**Comment by dongluochen** [comment]
LGTM
