### PR TITLE
Handle event monitor errors at engine.go

### LINKED ISSUE #2581: Swarm crashed with panic
`swarm version 1.2.3 (eaa53c7)`

I got this in the logs:
```
time="2016-12-29T09:35:05Z" level=error msg="HTTP error: Container 9681280172a9401f63cada000578e8627c00358e15986357df7533cafd0f1766 is paused, unpause the container before exec\n" status=500 
panic: runtime error: slice bounds out of range

goroutine 303036 [running]:
bufio.(*Writer).flush(0xc83dd9fb80, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:562 +0x2a7
bufio.(*Writer).Flush(0xc83dd9fb80, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:551 +0x2d
net/http.(*response).Flush(0xc82b7d16b0)
        /usr/local/go/src/net/http/server.go:1204 +0x45
github.com/docker/swarm/api.(*eventsHandler).Handle(0xc8202e7e60, 0xc83c8afb00, 0x0, 0x0)
        /go/src/github.com/docker/swarm/api/events.go:120 +0xebd
github.com/docker/swarm/cluster.(*EventHandlers).Handle(0xc820300ea0, 0xc83c8afb00)
        /go/src/github.com/docker/swarm/cluster/event.go:42 +0xff
github.com/docker/swarm/cluster/swarm.(*Cluster).Handle(0xc8202b38f0, 0xc83c8afb00, 0x0, 0x0)
        /go/src/github.com/docker/swarm/cluster/swarm/cluster.go:116 +0x3b
github.com/docker/swarm/cluster.(*Engine).handler(0xc820080dc0, 0xc839289ce0, 0x4, 0xc83b375e40, 0x40, 0xc8326479e0, 0x53, 0xc839289cf0, 0x9, 0xc839289d00, ...)
        /go/src/github.com/docker/swarm/cluster/engine.go:1198 +0x2d2
github.com/docker/swarm/cluster.(*Engine).(github.com/docker/swarm/cluster.handler)-fm(0xc839289ce0, 0x4, 0xc83b375e40, 0x40, 0xc8326479e0, 0x53, 0xc839289cf0, 0x9, 0xc839289d00, 0x4, ...)
        /go/src/github.com/docker/swarm/cluster/engine.go:211 +0x4e
github.com/docker/swarm/cluster.(*EventsMonitor).Start.func2(0x7f98c20b90c8, 0xc838896880, 0xc8388695a0, 0xc839118f60, 0xc838e69b00)
        /go/src/github.com/docker/swarm/cluster/event_monitor.go:70 +0x202
created by github.com/docker/swarm/cluster.(*EventsMonitor).Start
        /go/src/github.com/docker/swarm/cluster/event_monitor.go:76 +0x246

goroutine 1 [chan receive, 953 minutes]:
github.com/docker/swarm/api.(*Server).ListenAndServe(0xc8202e7dd0, 0x0, 0x0)
        /go/src/github.com/docker/swarm/api/server.go:118 +0x383
github.com/docker/swarm/cli.manage(0xc820120fc0)
        /go/src/github.com/docker/swarm/cli/manage.go:328 +0x18fd
github.com/docker/swarm/vendor/github.com/codegangsta/cli.Command.Run(0xf68158, 0x6, 0xf680f8, 0x1, 0x0, 0x0, 0x0, 0x1006a10, 0x17, 0x0, ...)
        /go/src/github.com/docker/swarm/vendor/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/docker/swarm/vendor/github.com/codegangsta/cli.(*App).Run(0xc820120d80, 0xc82000a0f0, 0x5, 0x5, 0x0, 0x0)
        /go/src/github.com/docker/swarm/vendor/github.com/codegangsta/cli/app.go:176 +0xfff
github.com/docker/swarm/cli.Run()
        /go/src/github.com/docker/swarm/cli/cli.go:68 +0x567
main.main()
        /go/src/github.com/docker/swarm/main.go:13 +0x14
...
```
[swarm-crash-20161229.zip](https://github.com/docker/swarm/files/677147/swarm-crash-20161229.zip)

### PR DESCRIPTION
**Pull request by dongluochen**
Fix #2581. Currently there could be multiple goroutines running `(*EventsMonitor).Start` for an engine and they introduce data race. There should be only 1 `EventsMonitor` goroutine for an engine.

`EOF` from Engine event stream is an Engine issue. Swarm needs to restart event monitor. This retry logic is in cluster/engine.go `StartMonitorEvents()`. 

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
Fix #2309.

File: cluster/event_monitor.go [hunk 1]
```diff
@@ -38,10 +38,6 @@ func (em *EventsMonitor) Start(ec chan error) {
 					return
 				}
 			case err := <-errStream:
-				if err == io.EOF {
```
Comment (nishanttotla) [inline cluster/event_monitor.go]: @dongluochen why does this check become redundant?

File: cluster/event_monitor.go [hunk 2]
```diff
@@ -27,9 +25,11 @@ func NewEventsMonitor(cli swarmclient.SwarmAPIClient, handler func(msg events.Me
 // Start starts the EventsMonitor
 func (em *EventsMonitor) Start(ec chan error) {
 	em.stopChan = make(chan struct{})
-	responseStream, errStream := em.cli.Events(context.Background(), types.EventsOptions{})
+	ctx, cancel := context.WithCancel(context.Background())
+	responseStream, errStream := em.cli.Events(ctx, types.EventsOptions{})
 
 	go func() {
+		defer cancel()
```
Comment (nishanttotla) [inline cluster/event_monitor.go]: Do we need to add a case to check `ctx.Done` here?

**Comment by nishanttotla** [comment]
Restarted the CI to confirm that test failures are unrelated.

File: cluster/event_monitor.go (hunk 1 above)
Comment (dongluochen) [inline cluster/event_monitor.go]: It's not redundant. It's a bug. For some reason, docker engine would send `EOF` on event stream. Swarm manager needs to restart the event stream upon receiving EOF. See https://github.com/docker/swarm/blob/master/cluster/engine.go#L217. Here we cannot translate `EOF` to nil error.

File: cluster/event_monitor.go (hunk 2 above)
Comment (dongluochen) [inline cluster/event_monitor.go]: This is a local empty context without deadline. There is no one but here to cancel it. So it's unnecessary to check `ctx.Done`.
