### PR TITLE
Periodically update node spec

### LINKED ISSUE #1281: Node labels only refreshed after Swarm Manager restart
If a node's labels are updated or changed, the changes aren't reflected in Swarm manager( even after restarting the engine). The only way to reflect these changes is to restart the Swarm Manager itself. 

Swarm Version: swarm/0.4.0
Node engine version: 1.8.2

Steps to Reproduce:
1. Update the labels on a node ( e.g add DOCKER_OPTS= --label=environment=production to /etc/default/docker)
2. Restart the node's engine 
3. Check the labels of that node on Swarm manager using 'docker info'
4. Restart the Swarm manager container itself.
5. Repeat Step 3 >> now you'll see the new labels

### PR DESCRIPTION
**Pull request by dongluochen**
Docker doesn't detect resource (CPU/Mem) change on the host so it cannot inform Swarm of such change. Swarm needs to updates node spec with some interval. It also updates node labels.  

Fix #1281, #1949. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by MHBauer** [comment]
Is a resource change something there should be an event for? This isn't the container changing cpussets, its the host cpusets changing, right?

**Comment by dongluochen** [comment]
@MHBauer Yes it's the host resource (CPU/Mem) or label change. Ideally Docker should emit events for change. But Docker doesn't track CPU/Mem in manifest. So it doesn't know there is a change.

File: cluster/engine.go [hunk 1]
```diff
@@ -692,6 +692,12 @@ func (e *Engine) updateContainer(c dockerclient.Container, containers map[string
 // refreshLoop periodically triggers engine refresh.
 func (e *Engine) refreshLoop() {
 	const maxBackoffFactor int = 1000
+	// engine can hot-plug CPU/Mem or update labels. but there is no events
+	// from engine to trigger spec update.
+	// add a update interval so a healthy node can update spec.
```
Comment (allencloud) [inline cluster/engine.go]: little typo: "a" -> "an"

**Comment by allencloud** [comment]
LGTM, label update is also included which will help me a lot.

**Comment by jimmyxian** [comment]
LGTM
