### PR TITLE
Reschedule containers with global network

### LINKED ISSUE #2149: swarm rescheduling doesnt work with overlay networks
I have 2 swarm nodes SwarmNode#1  and SwarmNode#2 
I created 8 containers , 4 of them with regular network, 4 of them with overlay network 
next I simulated downtime for SwarmNode#1 

after that swarm rescheduled only these containers which dont have overlay network 

for those which has overlay there is log in swarm manage:

Failed to start rescheduled container XXXXX: 500 Internal Server Error: service endpoint with name ubuntu07 already exists
Failed to start rescheduled container XXXXX: 500 Internal Server Error: service endpoint with name ubuntu06 already exists

### PR DESCRIPTION
**Pull request by dongluochen**
This PR supports container rescheduling with overlay network. Fix #2149. I ran some tests in a small cluster. More tests are welcome. 

Special thanks to @mavenugo for networking insight. cc @vieux @doronp. 

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

File: cluster/watchdog.go [hunk 1]
```diff
@@ -75,23 +80,76 @@ func (w *Watchdog) rescheduleContainers(e *Engine) {
 		// will abort because the name is already taken.
 		c.Engine.removeContainer(c)
 
-		newContainer, err := w.cluster.CreateContainer(c.Config, c.Info.Name, nil)
+		// keep track of all global networks this container is connected to
+		globalNetworks := make(map[string]*network.EndpointSettings)
+		// if the existing containter has global network endpoints,
+		// they need to be removed with force option
+		// "docker network disconnect -f network containername" only takes containername
```
Comment (allencloud) [inline cluster/watchdog.go]: Why does this command only take containername, not containerid?
It is really strange.

Comment (dongluochen) [inline cluster/watchdog.go]: IIRC, the node that owns this endpoint is disconnected. This command is run from another node, where it has  something like `ep-#containerid#`. Directly searching for containerid fails. 

@mavenugo Correct me if I'm wrong here.

**Comment by dongluochen** [comment]
@nishanttotla @allencloud please take a look.

File: cluster/watchdog.go [hunk 2]
```diff
@@ -61,6 +64,8 @@ func (w *Watchdog) rescheduleContainers(e *Engine) {
 	defer w.Unlock()
 
 	log.Debugf("Node %s failed - rescheduling containers", e.ID)
+
+reschduleLoop:
```
Comment (allencloud) [inline cluster/watchdog.go]: I am not sure if this label `reschduleLoop ` is necessary, as out of  `continue reschduleLoop` , there is only one `for` loop. @dongluochen

File: cluster/watchdog.go (hunk 1 above)
Comment (dongluochen) [inline cluster/watchdog.go]: Confirm with another test.

File: cluster/watchdog.go (hunk 2 above)
Comment (dongluochen) [inline cluster/watchdog.go]: Thanks @allencloud. Fixed.

File: cluster/watchdog.go [hunk 3]
```diff
@@ -75,23 +79,76 @@ func (w *Watchdog) rescheduleContainers(e *Engine) {
...
-			if c.Info.State.Running {
-				log.Infof("Container %s was running, starting container %s", c.ID, newContainer.ID)
-				if err := w.cluster.StartContainer(newContainer, nil); err != nil {
-					log.Errorf("Failed to start rescheduled container %s: %v", newContainer.ID, err)
-				}
+			continue
+		}
+
+		// Docker create command cannot create a container with multiple networks
+		// see https://github.com/docker/docker/issues/17750
```
Comment (nishanttotla) [inline cluster/watchdog.go]: seems like this issue was fixed, though we don't need to block this PR to fix that.

File: cluster/watchdog.go (hunk 1 above)
Comment (nishanttotla) [inline cluster/watchdog.go]: Confirmed this with @dongluochen. The only issue we noticed was conflicts in container name/id while searching, but that is a different unrelated issue.

**Comment by nishanttotla** [comment]
LGTM

**Comment by dongluochen** [comment]
Ping @allencloud, @abronan.

File: cluster/watchdog.go [hunk 4]
```diff
@@ -75,23 +79,76 @@ func (w *Watchdog) rescheduleContainers(e *Engine) {
 		// will abort because the name is already taken.
 		c.Engine.removeContainer(c)
 
-		newContainer, err := w.cluster.CreateContainer(c.Config, c.Info.Name, nil)
+		// keep track of all global networks this container is connected to
+		globalNetworks := make(map[string]*network.EndpointSettings)
+		// if the existing containter has global network endpoints,
```
Comment (abronan) [inline cluster/watchdog.go]: very nit: typo in comment: containter -> container

**Comment by abronan** [comment]
Overall LGTM, would be nice to have an integration test for this even though I don't recall us having overlay tests (afaik only local with bridge networking). Might be worth looking at libnetwork to see if they have an integration test that we can borrow and adapt :)

**Comment by dongluochen** [comment]
@abronan Thanks for the comment. Overlay testing is an issue to resolve. Let's treat it separately.

**Comment by yongshin** [comment]
I'm running Swarm 1.2.5 via UCP Swarm and tried to reschedule two containers that are connected via overlay networks. The following is my docker compose file and I shutdown app-node1 to see if they would be rescheduled on the swarm but did not see the containers being created and/or started.  

```
version: '2'

services:
  app:
    image: wordpress
    environment:
      - "WORDPRESS_DB_HOST=db:3306"
      - "WORDPRESS_DB_PASSWORD=wordpress"
      - "constraint:node==app-node1"
      - 'com.docker.swarm.reschedule-policies=["on-node-failure"]'
    ports:
      - 80
    depends_on:
      - db
    networks:
      - my-network
    restart: always

  db:
    restart: always
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=wordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
      - 'com.docker.swarm.reschedule-policies=["on-node-failure"]'
      - "constraint:node==app-node1"
    networks:
      - my-network
    volumes:
     - db:/data/db


volumes:
  db:
    driver: local

networks:
  my-network:
    driver: overlay
```

**Comment by yongshin** [comment]
An even more simplistic example does not work either, where one container is scheduled via compose. After killing the node that runs the container, there are no docker events that show the container being re-created an re-started. 

```
version: '2'

services:
  db:
    restart: always
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=wordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
      - 'com.docker.swarm.reschedule-policies=["on-node-failure"]'
      - "constraint:node==app-node1"
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local
```
